### ISSUE TITLE
Serving pyfunc model fails

### ISSUE THREAD

**Issue by camilocarvajalreyes** [camilocarvajalreyes/mlflow-nlp-example#2]
When running 
```mlflow models serve -m mlruns/0/b093c14327d7411a829b18102c6b8f8e/artifacts/Naive-Bayes_model -p 1234```
it first creates the corresponding conda env successfully. After that I get the following error message

```
2022/08/21 18:17:36 INFO mlflow.pyfunc.backend: === Running command 'source /home/camilo/miniconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e 1>&2 && exec gunicorn --timeout=60 -b 127.0.0.1:1234 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
[2022-08-21 18:17:36 -0400] [19772] [INFO] Starting gunicorn 20.1.0
[2022-08-21 18:17:36 -0400] [19772] [INFO] Listening at: http://127.0.0.1:1234 (19772)
[2022-08-21 18:17:36 -0400] [19772] [INFO] Using worker: sync
[2022-08-21 18:17:36 -0400] [19776] [INFO] Booting worker with pid: 19776
[2022-08-21 18:17:37 -0400] [19776] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/mlflow/pyfunc/scoring_server/wsgi.py", line 6, in <module>
    app = scoring_server.init(load_model(os.environ[scoring_server._SERVER_MODEL_PATH]))
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/mlflow/pyfunc/__init__.py", line 756, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/home/camilo/miniconda3/envs/mlflow-9f6ce72a9b8f5192c2d9daf4382c8d417578429e/lib/python3.10/site-packages/mlflow/pyfunc/model.py", line 273, in _load_pyfunc
    python_model = cloudpickle.load(f)
ModuleNotFoundError: No module named 'flavor'
[2022-08-21 18:17:37 -0400] [19776] [INFO] Worker exiting (pid: 19776)
[2022-08-21 18:17:37 -0400] [19772] [INFO] Shutting down: Master
[2022-08-21 18:17:37 -0400] [19772] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/home/camilo/miniconda3/envs/mlflow-test/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/mlflow/models/cli.py", line 68, in serve
    return _get_flavor_backend(
  File "/home/camilo/miniconda3/envs/mlflow-test/lib/python3.10/site-packages/mlflow/pyfunc/backend.py", line 261, in serve
    raise Exception(
Exception: Command 'exec gunicorn --timeout=60 -b 127.0.0.1:1234 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app' returned non zero return code. Return code = 3
```

**Comment by camilocarvajalreyes** [comment]
Solved by @GustavoSotoT on ef5d9b644563993fcf9b99011ca111f411b7bb8f.
