### ISSUE TITLE
Error when attempting to run train.py on Azure ML-studio

### ISSUE THREAD

**Issue by camilocarvajalreyes** [camilocarvajalreyes/mlflow-nlp-example#3]
When running naive_bayes/train.py from azure's terminal (ML-studio) I get the following exception:

```
Traceback (most recent call last):
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 76, in get_store_builder
    store_builder = self._registry[scheme]
KeyError: 'azureml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/camilo-small-ds11/code/Users/Camilo.Carvajal/mlflow-nlp-example/naive_bayes/train.py", line 31, in <module>
    with mlflow.start_run(run_name='testing-custom-flavor'):
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 278, in start_run
    client = MlflowClient()
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/client.py", line 66, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 51, in __init__
    self.store
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 55, in store
    return utils._get_store(self.tracking_uri)
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/utils.py", line 186, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/registry.py", line 48, in _get_store_with_resolved_uri
    builder = self.get_store_builder(resolved_store_uri)
  File "/anaconda/envs/mlflow-test/lib/python3.10/site-packages/mlflow/tracking/registry.py", line 78, in get_store_builder
    raise UnsupportedModelRegistryStoreURIException(
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'azureml://westeurope.api.azureml.ms/mlflow/v1.0/subscriptions/97675fc5-d0b8-4930-a9b7-72eb6343dff9/resourceGroups/rg-psw-dev-003/providers/Microsoft.MachineLearningServices/workspaces/mlw-psw-dev-003' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

ERROR conda.cli.main_run:execute(49): `conda run python naive_bayes/train.py 4 0.9` failed. (See above for error)
```

**Comment by camilocarvajalreyes** [comment]
solved executing

`pip install azureml-mlflow`
